# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=200)),
                ('user_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
